# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'Lit & Data'
tagline:             'Summer 2019'
description:         'Course site for ENGL-UA 735: Readings in Contemporary Literature @ NYU'
url:                 https://gafsari.github.io
baseurl:             '/lanyon'
paginate:            5

# About/contact
author:
  name:              Grace Afsari-Mamagani
  email:             gafsari@nyu.edu

# Custom vars
version:             1.0.0
